[project]
name = "before-push"
version = "0.1.4"
description = "A small CLI that checks your current Git branch before you push or open a pull request."
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "rich>=15.0.0",
]

[dependency-groups]
dev = [
    "mkdocs-material>=9.7.7",
    "pytest>=9.1.1",
    "ruff>=0.13.0",
]

[project.scripts]
beforepush = "cli:main"

[tool.uv]
package = true
